### PR TITLE
World Edit

### PR DESCRIPTION
**Pull request by Janjre**
World Edit commands for Onix.

### CODE REVIEW

**Comment by jqms** [comment]
holy shit

why are you using chatmessageaddedd rather then registerCommand?

**Comment by Janjre** [comment]
> holy shit
> 
> why are you using chatmessageaddedd rather then registerCommand?

i didnt know it existed lol

**Comment by jqms** [comment]
whats your discord?

**Comment by jqms** [comment]
also here is a nicer looking help command

            local keywordColor = "§e"  -- Yellow color for keywords
            local usageColor = "§a"    -- Green color for usage
            local dividerColor = "§f"  -- Grey color for dividers
            
            print("Select 2 positions using a wooden sword then type one of the commands to affect that area.\n" ..
                  "When the syntax says \"block\", it means either something like \"dirt\" or something like \"50%dirt,50%air\"\n" ..
                  dividerColor .. "------------------------------\n" ..
                  keywordColor .. "$fill§r " .. dividerColor .. "| §7runs a normal fill command " .. dividerColor .. "| §7" .. usageColor .. "$fill§r <block>\n" ..
                  keywordColor .. "$replace§r " .. dividerColor .. "| §7replaces all of the first argument's block to the second within the selected range " .. dividerColor .. "| §7" .. usageColor .. "$replace§r <replacewhat> <replacewith>\n" ..
                  keywordColor .. "$line§r " .. dividerColor .. "| §7creates a line between the two selected points " .. dividerColor .. "| §7" .. usageColor .. "$line§r <block> [width/precision]\n" ..
                  keywordColor .. "$mirror§r " .. dividerColor .. "| §7mirrors one side of the blue line to the other. Doesn't work with block states" .. dividerColor .. "| §7" .. usageColor .. "$mirror§r\n" ..
                  keywordColor .. "$wall§r " .. dividerColor .. "| §7creates a wall between two points " .. dividerColor .. "| §7" .. usageColor .. "$wall§r <block> [width/precision]\n" ..
                  keywordColor .. "$infinitewater§r " .. dividerColor .. "| §7all non-source water blocks get turned into sources so can spread infinitely in any direction aside from up\n" ..
                  dividerColor .. "------------------------------\n" ..
                  keywordColor .. "$circle§r " .. dividerColor .. "| §7makes a circle with the radius of the distance between the two selected points (the center being the first) " .. dividerColor .. "| §7" .. usageColor .. "$circle§r <x or y> <block> [true/false:fill]\n" ..
                  keywordColor .. "$sphere§r " .. dividerColor .. "| §7makes a sphere with the radius of the distance between the two selected points " .. dividerColor .. "| §7" .. usageColor .. "$sphere§r <block> [true/false:fill]\n" ..
                  keywordColor .. "$HUD§r " .. dividerColor .. "| §7toggles the coordinates of the two selected points " .. dividerColor .. "| §7" .. usageColor .. "$HUD§r\n" ..
                  keywordColor .. "$build-up§r " .. dividerColor .. "| §7duplicates all of the specified block up a specified amount of times " .. dividerColor .. "| §7" .. usageColor .. "$build-up§r <block> <height>\n" ..
                  keywordColor .. "$help§r " .. dividerColor .. "| §7I think you already know how to use this one " .. dividerColor .. "| §7" .. usageColor .. "$help§r\n" ..
                  keywordColor .. "$pos1§r " .. dividerColor .. "| §7sets position 1 to your current coordinates (your feet) " .. dividerColor .. "| §7" .. usageColor .. "$pos1§r\n" ..
                  keywordColor .. "$pos2§r " .. dividerColor .. "| §7same as pos1 " .. dividerColor .. "| §7" .. usageColor .. "$pos2§r\n" ..
                  keywordColor .. "$up§r " .. dividerColor .. "| §7teleports you up a specified amount of blocks upward and places a block below you " .. dividerColor .. "| §7" .. usageColor .. "$up§r <height>\n" ..
                  keywordColor .. "$thrutool§r " .. dividerColor .. "| §7when pressed against a block click and it will teleport you to the other side of the block/s (intended for going in and out of builds without using a door). Limit of 356 blocks " .. dividerColor .. "| §7" .. usageColor .. "$thrutool§r\n" ..
                  dividerColor .. "------------------------------\n" ..
                  keywordColor .. "$copy§r " .. dividerColor .. "| §7Copies the selected area to a file in ..scripts\\data " .. dividerColor .. "| §7" .. usageColor .. "$copy§r\n" ..
                  keywordColor .. "$paste§r " .. dividerColor .. "| §7pastes the file in the file with no rotational changes. !!WARNING!! This function is laggy and doesn't work with block states on 1.20 blocks. If you're pasting very precisely or a large build, use structure blocks instead. " .. dividerColor .. "| §7" .. usageColor .. "$paste§r [true/false:skip/keep air]\n" ..
                  keywordColor .. "$wand§r " .. dividerColor .. "| §7gives you a wooden sword " .. dividerColor .. "| §7" .. usageColor .. "$wand§r")

**Comment by Janjre** [comment]
thx

**Comment by Janjre** [comment]
discord:HushedCandle753#1303

**Pull request merged**
